### ISSUE TITLE
Support *.tsx

### ISSUE THREAD

**Issue by Wildhoney** [andywer/ava-ts#4]
Although `*.ts` files seem to run perfectly well, I'm having trouble getting `*.tsx` files to be recognised.

With `ava-ts **/*.test.{ts,tsx}` it claims it cannot find any `*.tsx` files, but finds an abundance of `*.ts` files and runs them successfully. I've tried renaming my `.tsx` files to `.ts`, and although `ava-ts` then finds them, it fails to compile &mdash; potentially because they now have an incorrect extension, or it may be an additional issue to resolve.

Do you have any examples of how to add support for `.tsx`?

**Comment by andywer** [comment]
Hey @Wildhoney!

#1 introduced the changes in file name matching. We could just add `*.tsx` in all the necessary places.

To be fair - AVA does not seem to match `*.jsx` either. I would rather suggest renaming to `*.ts`, since renaming the file the moment you add the first bit of JSX or removing the only JSX snippet sucks. But this is just my personal opinion 😉

I am pretty sure there is something else wrong if it didn't work with the renamed files either. Maybe you can provide an example?

**Comment by Wildhoney** [comment]
I'm not a huge fan of TS, and I totally agree with you regarding the renaming from `.ts` to `.tsx`. In projects that I setup and manage, I have all of the JSX in `.js` files. However unfortunately this isn't my project.

I will investigate further today, and update the ticket if I find anything.

**Comment by andywer** [comment]
Fixed in v0.24.1.
